site_name: pyRedunda
site_url: https://sobotics.org
repo_url: https://github.com/SOBotics/pyRedunda
repo_name: pyRedunda
site_description: A python library for using Redunda.

pages:
 - Home: 'index.md'
 - 'Introduction': 'whatis.md'
 - 'Installation': 'installation.md'
 - 'Constructing a Redunda object': 'setup.md'
 - 'Status pings': 'statusping.md'
 - 'Uploading and Downloading files': 'files.md'
 - 'Handling events': 'events.md' 
